### ISSUE TITLE
Add support for configuring the java version to be used (set java home)

### ISSUE THREAD

**Issue by mesl** [TechnicPack/LauncherV3#30]
When Java 8 is installed some modpack refuse to work. By configuring the java home to be used, it is possible to use these modpacks with a different java version.

**Comment by CannibalVox** [comment]
These PR's are a good start.  I'd like something like the FTB launcher has, though, where it autodetects installed java versions and lists them in there immediately.  I'd also like the underlying code to understand whether a given java install is 32 or 64 bit and the java version in order to both support different RAM allocations and also future plans for solder.

**Comment by CannibalVox** [comment]
If you want to take care of that stuff, it'd be very helpful.  Otherwise I'll leave these open until I finish byte-patching then I'll merge them & finish it up myself.

**Comment by CannibalVox** [comment]
This was put live in a hotfix this weekend, it's a little bit more featureful than what was suggested here.
