### ISSUE TITLE
technic Launcher Doesn't Work With Downloading Packs

### ISSUE THREAD

**Issue by jredfox** [TechnicPack/LauncherV3#66]
There is a lack of coding in the technic launcher api that makes it not work with the only website that has no bandwidth limits that could posibly be a file hosting services that is not a dedicated server that you would pay minimum of 30.00 a month or ocean digetal which you pay who knows how much plus 80.00 in data usage per month from the downloads of a popular modpack.  So you need to fix it so it works with mediafire.com they change there source links every day So I am not changing my source links every day or pay 30.00 a month just because you refuse to update your api to grap the source link from mediafire when it seemed to work with the server pack and mediafire a couple months ago that's outrageous.  you need to fix this at once. there is no possible way to host an account **even dropbox premium dropped me in just 6 hours from 2k downloads of ekims advanced rpg modpack**.  what then I did Is I compared all of your hosts and have looked for the past 2 weeks and non of them seem to support dirrect url downloads such as replacing the www with dl just so your api would be happy to download it.  it needs to be more compat to work. this is insuficent evidence that your technic launcher is currently able to host a popular modpack without paying big bucks per month which I don't have.  Mediafire is a free no limit in bandwidth hosting add compatibility for that everybody uses that for public file hosting.  get that to work.

**Comment by khionu** [comment]
Alternative? http://lmgtfy.com/?q=unlimited+bandwidth+file+hosting+direct+link

**Comment by khionu** [comment]
Another point..... nothing is free. As some point, someone paid for something. Someone put out the expenses. Things that are free to the end-user are a *gift* to the public. Massive downloads? Hogging. It makes the need to get your own. Which means cost. If you don't like that? Tough. Technic is not the only place you will run into this. That's why I pay $70/month (which includes setup fee) for a Dedicated Server, so I don't have to deal with limits.

Last point.... Technic is such a gift to the public, by a team that loves what they do. They are under no obligation to bend to you.

**Comment by jredfox** [comment]
mediafire.com is a free user freindly services that you don't pay for and no bandwidth limit.

**Comment by jredfox** [comment]
yes it was I looked for hours they mostly don't support dirrect links or no bandwidth ocean digitel is the best for 5.00 a month. however it's not free and mediafire is update the launcher canival vox
